#!/usr/bin/env python3
"""Regenerate lean/MathCorpus.lean to import every module under lean/MathCorpus/.

Keeps the library root in sync with the proof files the packets reference, so a
`lake build MathCorpus` covers the whole corpus.

Usage:
    python tools/gen_lean_root.py
"""

from __future__ import annotations

from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
LEAN_ROOT = REPO / "lean"
SRC = LEAN_ROOT / "MathCorpus"


def main() -> int:
    modules = []
    for p in sorted(SRC.rglob("*.lean")):
        rel = p.relative_to(LEAN_ROOT).with_suffix("")
        modules.append(".".join(rel.parts))
    lines = [
        "-- MathCorpus formal library root.",
        "-- Auto-generated by tools/gen_lean_root.py; do not edit by hand.",
        "-- Each public formal packet references a module under `MathCorpus/`.",
    ]
    lines += [f"import {m}" for m in modules]
    (LEAN_ROOT / "MathCorpus.lean").write_text("\n".join(lines) + "\n",
                                               encoding="utf-8", newline="\n")
    print(f"MathCorpus.lean: {len(modules)} module(s)")
    for m in modules:
        print(f"  {m}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
